### ISSUE TITLE
建议添加本学期GPA统计

### ISSUE THREAD

**Issue by AgainstWar** [Mystery00/XhuTimetable#1]
课程成绩查询中已经能够实现学分和绩点的查询，在此基础上套公式计算出GPA应该不是难事。
大致的想法
- [x] 统计GPA\总学分\平均成绩
- [x] 在 _最下方_ 或 _**通过课程列表**右侧_ 按**一定格式**显示出来

**Comment by Mystery00** [comment]
GPA的计算规则是怎样的呢？

**Comment by AgainstWar** [comment]
有两种思路，按需选择

1. $$GPA=\frac{(平均成绩-50)}{10}$$

2. $$GPA=\frac{总成绩}{总绩点}$$

**Comment by Mystery00** [comment]
已经在最新版本中添加该功能，关于GPA计算是否准确还需要你们在校学生帮忙看看

**Comment by AgainstWar** [comment]
GPA的计算有一点小问题
应该在现在的基础上再加一行代码:
`GPA=(GPA-50)/10` 
>保留两位小数且四舍五入

**Comment by Mystery00** [comment]
> GPA的计算有一点小问题 应该在现在的基础上再加一行代码: `GPA=(GPA-50)/10`
> 
> > 保留两位小数且四舍五入

https://github.com/Mystery00/XhuTimetable/blob/7cbeecbf8c8cd4e7639545e77ff122e6e78f20b5/app/src/main/java/vip/mystery0/xhu/timetable/ui/activity/ScoreActivity.kt#L567

这一行确实计算错了，应该是通过的所有成绩中的 sum(绩点x学分)/sum(学分)

**Comment by Mystery00** [comment]
> GPA的计算有一点小问题 应该在现在的基础上再加一行代码: `GPA=(GPA-50)/10`
> 
> > 保留两位小数且四舍五入

现在重新按照正确的计算方式进行计算了（服务端计算），GPA=sum(单科学分x单科绩点)/sum(单科学分)

**Comment by Mystery00** [comment]
相关代码如下：
```kotlin
val scoreList = scoreDao.getScore(username, year, term, queryModel).items
            .filter { it.scoreType == "正常考试" }
        val totalScore = scoreList.sumOf {
            runCatching { it.score.toDouble() }.getOrElse { 0.0 }
        }
        val totalCredit = scoreList.sumOf {
            runCatching { it.credit.toDouble() }.getOrElse { 0.0 }
        }
        val totalGpa = scoreList.sumOf {
            runCatching { it.credit.toDouble() }.getOrElse { 0.0 } * it.creditGpa
        }
        return ScoreGpa(
            totalScore = totalScore,
            averageScore = totalScore / scoreList.size,
            totalCredit = totalCredit,
            gpa = totalGpa / totalCredit,
        )
```
