### ISSUE TITLE
无法获取实验课所在教室

### ISSUE THREAD

**Issue by AgainstWar** [Mystery00/XhuTimetable#2]
在教务系统中的实验课表查询处可以查询到具体上课地点，但软件中却没有显示。
> 目前仅发现专业实验课出现该情况

![photo1](https://user-images.githubusercontent.com/61017766/232316376-913ce318-4bfc-4404-8f78-3a6f93b47335.png)

![Screenshot_20230416_220041](https://user-images.githubusercontent.com/61017766/232316447-09e1402f-85de-4be3-ab43-d9b060e05d32.jpg)

**Comment by Mystery00** [comment]
> 在教务系统中的实验课表查询处可以查询到具体上课地点，但软件中却没有显示。
> 
> > 目前仅发现专业实验课出现该情况
> 
> ![photo1](https://user-images.githubusercontent.com/61017766/232316376-913ce318-4bfc-4404-8f78-3a6f93b47335.png)
> 
> ![Screenshot_20230416_220041](https://user-images.githubusercontent.com/61017766/232316447-09e1402f-85de-4be3-ab43-d9b060e05d32.jpg)

方便加一下交流反馈群私聊提供一下账号信息吗，实验课表是根据大学物理实验进行的解析，可能的专业实验课的相关字段不同导致的

**Comment by AgainstWar** [comment]
这是电气类专业实验课，看了看代码，应该是教务处那边校区显示为 undefined 的问题（本来该是郫都校区）

**Comment by Mystery00** [comment]
校区为undefined不应该影响上课地点的解析，请问是什么专业呢，我看看能不能在群里找个人提供一下账号，看一下相关的解析流程

**Comment by AgainstWar** [comment]
电气工程及其自动化、信息工程和通信工程均出现此情况

**Comment by Mystery00** [comment]
校本部对吧，我去群里问问

**Comment by Mystery00** [comment]
找到原因了，是因为这种类型的实验课，上课地点使用了不同的字段返回数据，所以我们添加了额外的解析逻辑用于兼容这种情况，目前已经修复，现在再调用接口应该能够得到正确数据了
