### ISSUE TITLE
关于完成教学质量评价的问题

### ISSUE THREAD

**Issue by wifi504** [Mystery00/XhuTimetable#4]
如果未在教务系统完成教学质量评价，西瓜课表的全部查询功能都将不可用，但是你直接使用教务系统进行查询，如果事先存储了对应查询的API，直接访问将直接获得查询结果，完全可以绕过完成教学质量评价，不知道西瓜课表代理的教务系统API为什么会无法使用

**Comment by Mystery00** [comment]
刻意为之，不要和学校对着干
